dist: trusty
sudo: true

language: node_js
node_js:
  - '12.8.0'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - "python3"
      - "python3-pip"

cache:
  directories:
    - ./client/node_modules

before_install: 
  - cd client

install:
  - npm install

script:
  - echo "skipping tests"

before_deploy:
  - ng build --prod
  - pip3 install awscli

deploy:
  provider: script
  script: aws s3 sync dist/client s3://sls-streaming --region=us-east-2 --delete
  skip_cleanup: true
  on:
    branch: master