version: '3'
services:
  redditproducer:
    container_name: redditproducer
    build:
      context: ./redditproducer
    volumes:
      - './redditproducer:/app'
    depends_on:
      - kafka
      - zookeeper
    env_file:
      - reddit.env
  twitterproducer:
    container_name: twitterproducer
    build:
      context: ./twitterproducer
    volumes:
      - './twitterproducer:/app'
    depends_on:
      - kafka
      - zookeeper
    env_file:
      - twitter.env
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    tmpfs: "/datalog"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    depends_on:
      - zookeeper
    environment:
      HOSTNAME_COMMAND: "echo $$(hostname)"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_PORT: 9092
      BROKER_ID_COMMAND: "docker inspect --format '{{ .Name }}' $$(hostname) | awk -F_ '{ printf $$NF }'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "reddit:1:1,twitter:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
